version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/static  
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: ./app 
    #image: 320183397498.dkr.ecr.us-east-1.amazonaws.com/kozijakinfo/skillset-app:1.0
    container_name: web
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
    ports:
      - "3606:3606"
    volumes:
      - skillset_volume:/var/lib/mysql

volumes:
  skillset_volume:
    name: skillset_db_volume
    
